In [17]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model

In [18]:
df=pd.read_csv ("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
df.info

<bound method DataFrame.info of   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000>

In [21]:
df["test_score(out of 10)"]

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score(out of 10), dtype: float64

In [7]:
# Utilisez .rename() pour renommer les colonnes
df = df.rename(columns={'test_score(out of 10)': 'test_score', 'interview_score(out of 10)': 'interview_score'})

# Affichez le DataFrame avec les nouvelles colonnes
print(df)


Empty DataFrame
Columns: []
Index: []


In [8]:
df

Empty DataFrame
Columns: []
Index: []

In [22]:
import math
median_test_score = math.floor(df["test_score(out of 10)"].median())
median_test_score

8

In [23]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5590 sha256=17cfeb7dade55cba1c4131dc1d636f9f3e73d85b300014641439990485cdb729
  Stored in directory: c:\users\panla\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
df["experience"] = df["experience"].fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [28]:
from word2number import w2n
df['experience_number'] = df['experience'].apply(lambda x: w2n.word_to_num(x))

In [29]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0       zero                    8.0                           9      50000   
1       zero                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    8.0                           7      72000   
7     eleven                    7.0                           8      80000   

   experience_number  
0                  0  
1                  0  
2                  5  
3                  2  
4                  7  
5                  3  
6                 10  
7                 11

In [30]:
median_experience_number = math.floor(df["experience_number"].median())
median_experience_number

4

In [32]:
df['experience_number'] = df['experience_number'].replace({0: median_experience_number})
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0       zero                    8.0                           9      50000   
1       zero                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    8.0                           7      72000   
7     eleven                    7.0                           8      80000   

   experience_number  
0                  4  
1                  4  
2                  5  
3                  2  
4                  7  
5                  3  
6                 10  
7                 11

In [33]:
reg = linear_model.LinearRegression ()
X=df[["test_score(out of 10)","interview_score(out of 10)","experience_number"]]
y=df["salary($)"]
reg.fit(X,y)

LinearRegression()

In [34]:
reg.coef_

array([1803.45158198, 3184.69450013, 3390.87422644])

In [35]:
reg.intercept_

4220.822801359682

In [36]:
reg.predict([[9,6,2]])

c:\Users\panla\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46341.80249281])

In [37]:
reg.predict([[10,10,12]])

c:\Users\panla\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94792.77433975])